-- Skills navigation assessment for recruiting candidates.
--
-- One row per generated test link. An applicant opens a public (no-login) page
-- at /skills-test/:token and completes a simulated CRM test (find a record,
-- edit + save a field, move between windows, copy + paste). Results are written
-- back by the `skills-assessment` edge function using the service role, which
-- bypasses RLS. Staff generate links and read results through the app, gated by
-- is_leadership() like the other recruiting_* tables.

CREATE TABLE IF NOT EXISTS public.recruiting_skill_assessments (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  candidate_id  uuid NOT NULL
                  REFERENCES public.recruiting_candidates(id) ON DELETE CASCADE,
  -- URL-safe random string generated by the app; unguessable link identifier.
  token         text NOT NULL UNIQUE,
  status        text NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','in_progress','completed','expired')),
  created_at    timestamptz NOT NULL DEFAULT now(),
  created_by    uuid DEFAULT auth.uid()
                  REFERENCES auth.users(id) ON DELETE SET NULL,
  started_at    timestamptz,
  completed_at  timestamptz,
  -- Total wall-clock seconds the applicant spent on the test.
  total_seconds integer,
  -- Per-task raw breakdown: completed y/n, seconds, hints used, method (e.g.
  -- searched vs scrolled), correctness. Shape owned by the test page; kept as
  -- jsonb so the task set can evolve without a schema change.
  results       jsonb
);

CREATE INDEX IF NOT EXISTS idx_recruiting_skill_assessments_candidate
  ON public.recruiting_skill_assessments (candidate_id, created_at DESC);

ALTER TABLE public.recruiting_skill_assessments ENABLE ROW LEVEL SECURITY;

-- Staff access mirrors the rest of the recruiting module. The public applicant
-- path never touches the table directly; the edge function uses the service
-- role (exempt from RLS), so no anon/public policy is defined here.
DROP POLICY IF EXISTS recruiting_skill_assessments_leadership_all
  ON public.recruiting_skill_assessments;

CREATE POLICY recruiting_skill_assessments_leadership_all
  ON public.recruiting_skill_assessments
  FOR ALL
  USING (public.is_leadership())
  WITH CHECK (public.is_leadership());
